[capture]
win_title = "Stormworks"
win_text = ""
win_exclude_title = ""
win_exclude_text = ""

screen_width = 1920
screen_height = 1080

scroll_x = 960
scroll_y = 540
scroll_page_n = 1024
scroll_once_n = 3
scroll_threshold = 0

capture_area_x1 = 312
capture_area_y1 = 226
capture_area_x2 = 1285
capture_area_y2 = 763
capture_template_ratio = 0.25

activate_sleep_secs = 5
scroll_sleep_secs = 3

[recognize]
head_thresh_s = 9
body_line_h = 21
code_thresh_x = 9
code_base_x = 14
code_indent_w = 38
code_line_h = 16.5
bg_thresh_r = 40
bg_thresh_g = 40
bg_thresh_b = 40
