[capture]
win_class = "GLFW30"
win_title = "Stormworks"

screen_width = 1920
screen_height = 1080

scroll_x = 960
scroll_y = 540
scroll_init_delta = 122880
scroll_down_delta = -360
scroll_threshold = 0

capture_area_x = 312
capture_area_y = 226
capture_area_w = 1285
capture_area_h = 763
capture_template_ratio = 0.25

activate_delay = 5
scroll_mouse_delay = 0.1
scroll_smooth_delay = 3

[recognize]
preprocess_scale = 2
head_thresh_s = 9
body_line_h = 21
code_thresh_x = 9
code_base_x = 14
code_indent_w = 38
code_line_h = 16.5
bg_thresh_r = 40
bg_thresh_g = 40
bg_thresh_b = 40
